{{- if .Values.secrets.useProvidedMonitoringToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.crusoeMonitoringToken }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  CRUSOE_MONITORING_TOKEN: {{ .Values.secrets.monitoringToken | b64enc | quote }}
{{- end }}
