{{- if not .Values.secrets.useProvidedMonitoringToken }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  namespace: {{ .Values.namespace }}
spec:
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    spec:
      serviceAccountName: secret-manager-sa
      restartPolicy: Never
      containers:
        - name: crusoe-token-creator
          image: {{ .Values.job.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: CRUSOE_NAMESPACE
              value: {{ .Values.namespace }}
            - name: CRUSOE_MONITORING_TOKEN_SECRET_NAME
              value: {{ .Values.secrets.crusoeMonitoringToken }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.existingSecret }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
{{- end }}
