{{- $customMetricsNs := .Values.customMetrics.namespace | default "crusoe-monitoring" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: crusoe-custom-metrics-config
  namespace: {{ $customMetricsNs }}
data:
  custom-metrics-config.yaml: |
    default_scrape_interval_sec: 30

    fake-metrics-app:
      allowlist:
        - my_app_requests_total
