{{- if and .Values.logCollector.enabled .Values.vector.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.logCollector.name }}
  labels:
    app: {{ .Values.logCollector.name }}
    app.kubernetes.io/name: {{ .Values.logCollector.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  # Need to list and get pods to find NVIDIA driver pods
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  # Need to exec into pods to run nvidia-bug-report.sh
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.logCollector.name }}
  labels:
    app: {{ .Values.logCollector.name }}
    app.kubernetes.io/name: {{ .Values.logCollector.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.logCollector.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.vector.serviceAccount.name | default "crusoe-watch-agent" }}
    namespace: {{ .Values.namespace }}
{{- end }}