apiVersion: v1
entries:
  crusoe-watch-agent:
  - apiVersion: v2
    created: "2026-02-13T19:44:12.911771563Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent, Crusoe Log Collector and
      monitoring token job
    digest: 77651c86eb3752b9d35362b777a0b33027fb27ef9cf768ba84ce5716e476328c
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.3.7.tgz
    version: 0.3.7
  - apiVersion: v2
    created: "2026-02-13T19:44:12.908469582Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent, Crusoe Log Collector and
      monitoring token job
    digest: 73200a7acca415be91fa68c7aab1a129b27d249ecd37597b800e441065664c2b
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.3.6.tgz
    version: 0.3.6
  - apiVersion: v2
    created: "2026-02-13T19:44:12.90419059Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent, Crusoe Log Collector and
      monitoring token job
    digest: 667b456fbe09a14dc054b4a74ed7718be436600e1503b65ad437ad22f7e4f1ea
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.3.5.tgz
    version: 0.3.5
  - apiVersion: v2
    created: "2026-02-13T19:44:12.900867729Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent and monitoring token job
    digest: 5b7010729f6580051c3042d9095d80fec89e17d17b8d540769e58d7cc8783a71
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.3.4.tgz
    version: 0.3.4
  - apiVersion: v2
    created: "2026-02-13T19:44:12.896630671Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent and monitoring token job
    digest: 0514e792a27309f8e973ddb94872123a3f0e72186cc9489866ddd70b1e401a34
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.3.3.tgz
    version: 0.3.3
  - apiVersion: v2
    created: "2026-02-13T19:44:12.893279567Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent and monitoring token job
    digest: 5633c8985b4040cf0090d8cca3242ae0cc9e25f6d3747d0722eb9848a51496fa
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.3.2.tgz
    version: 0.3.2
  - apiVersion: v2
    created: "2026-02-13T19:44:12.888969738Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent and monitoring token job
    digest: ac0abe38fd8919f72267b595ad567185d29d0ac3ce3a4e6c1995a306a912cd9f
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    created: "2026-02-13T19:44:12.885000319Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent and monitoring token job
    digest: 7038ddd779e496a3ddecb0d26987f510e81e66b437eb1b37d82cc4bf084543e0
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    created: "2026-02-13T19:44:12.880818288Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent and monitoring token job
    digest: 78ca5ae996f834d7de9ec3f64754221df724963bc7a8f74757094643b98b8314
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v2
    created: "2026-02-13T19:44:12.877017774Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent and monitoring token job
    digest: 47b3900bfeff5d4b4696bb6885ca5b3ccae4f3827a57daaa9df738e719de3683
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v2
    created: "2026-02-13T19:44:12.873140588Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent and monitoring token job
    digest: fa359b76c90a050b350cba2125f59ca20afd2fd2c94d60a0fcfba72d6341115a
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.2.6.tgz
    version: 0.2.6
generated: "2026-02-13T19:44:12.868476255Z"
