apiVersion: v1
entries:
  crusoe-watch-agent:
  - apiVersion: v2
    created: "2026-02-06T19:44:22.219568362Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent and monitoring token job
    digest: 48481e7c2fbc28c01fb2e57aac184ecd50d6556c6494da9dbdabe02b1118c74f
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    created: "2026-02-06T19:44:22.215737844Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent and monitoring token job
    digest: 7038ddd779e496a3ddecb0d26987f510e81e66b437eb1b37d82cc4bf084543e0
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    created: "2026-02-06T19:44:22.21156263Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent and monitoring token job
    digest: 78ca5ae996f834d7de9ec3f64754221df724963bc7a8f74757094643b98b8314
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.2.8.tgz
    version: 0.2.8
  - apiVersion: v2
    created: "2026-02-06T19:44:22.208133255Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent and monitoring token job
    digest: 47b3900bfeff5d4b4696bb6885ca5b3ccae4f3827a57daaa9df738e719de3683
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.2.7.tgz
    version: 0.2.7
  - apiVersion: v2
    created: "2026-02-06T19:44:22.204091967Z"
    dependencies:
    - name: vector
      repository: https://helm.vector.dev
      version: 0.45.0
    description: Helm chart to deploy Crusoe Watch Agent and monitoring token job
    digest: fa359b76c90a050b350cba2125f59ca20afd2fd2c94d60a0fcfba72d6341115a
    name: crusoe-watch-agent
    type: application
    urls:
    - https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts/crusoe-watch-agent-0.2.6.tgz
    version: 0.2.6
generated: "2026-02-06T19:44:22.200489211Z"
