apiVersion: v1
kind: ConfigMap
metadata:
  name: crusoe-custom-metrics-config
  namespace: crusoe-monitoring
data:
  custom-metrics-config.yaml: |
    default_scrape_interval_sec: 30

    fake-metrics-app:
      allowlist:
        - my_app_requests_total
