apiVersion: v2
name: crusoe-watch-agent
description: Helm chart to deploy Crusoe Watch Agent, Crusoe Log Collector and monitoring token job
type: application
version: 0.3.9
dependencies:
  - name: vector
    version: "0.45.0"
    repository: "https://helm.vector.dev"
