name: HELM Package CI
on:
  push:
    branches:
      - main
    paths:
      - 'k8s/helm-charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_PAT }}

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Package chart
        run: |
          mkdir -p docs/k8s/helm-charts
          helm package ./k8s/helm-charts -d docs/k8s/helm-charts
          helm repo index docs/k8s/helm-charts --url https://crusoecloud.github.io/crusoe-watch-agent/k8s/helm-charts

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/k8s/helm-charts
          git commit -m "Update helm repo"
          git push
